"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResetCounter = exports.IncrementCounter = void 0;
const web3_1 = require("@alephium/web3");
const contracts_1 = require("./contracts");
const IncrementCounter_ral_json_1 = __importDefault(require("../IncrementCounter.ral.json"));
const ResetCounter_ral_json_1 = __importDefault(require("../ResetCounter.ral.json"));
const types_1 = require("./types");
exports.IncrementCounter = new web3_1.ExecutableScript(web3_1.Script.fromJson(IncrementCounter_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.ResetCounter = new web3_1.ExecutableScript(web3_1.Script.fromJson(ResetCounter_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
